default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: nuuvem_dev_challenge
  password: 99336622
  host: localhost

development:
  <<: *default
  database: nuuvem_dev_challenge_development

test:
  <<: *default
  database: nuuvem_dev_challenge_test

production:
  <<: *default
  database: nuuvem_dev_challenge_production
  username: nuuvem_dev_challenge
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: your_production_host
